name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/flask-backend:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/flask-backend:latest

      - name: Deploy Container with Docker Compose
        run: |
          docker run -d -p 5000:5000 --name flask-app ghcr.io/${{ github.repository }}/flask-backend:latest
